name: Provision AWS EC2 with Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Init & Apply Terraform
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Get EC2 IP
      id: get_ip
      working-directory: terraform
      run: |
        echo "EC2_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

    # - name: Wait for EC2 to start
    #   run: sleep 60

    # - name: Install Docker & Deploy App
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ env.EC2_IP }}
    #     username: ubuntu
    #     key: ${{ secrets.PRIVATE_KEY }}
    #     script: |
    #       sudo apt update
    #       sudo apt install -y docker.io
    #       sudo docker run -d -p 80:5000 ghcr.io/<your-user>/<your-repo>:latest
